name: Lint & Test
on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Run linter
        run: go fmt

      - name: Run tests
        run: go test -v ./...
